# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('type', models.CharField(choices=[('Bungalow', 'Bungalow'), ('Apartment', 'Apartment'), ('Villa', 'Villa')], default='Bungalow', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai')], default='Mumbai', max_length=10)),
                ('bathrooms', models.IntegerField(default=0, null=True)),
                ('bedrooms', models.IntegerField(default=0, null=True)),
                ('garages', models.IntegerField(default=0, null=True)),
                ('rooms', models.IntegerField(default=0, null=True)),
                ('area', models.IntegerField()),
                ('price', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Property', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/properties/')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='PropertyImage', to='PropertyBazaar.Property')),
            ],
            options={
                'verbose_name': 'PropertyImage',
                'verbose_name_plural': 'PropertyImages',
            },
        ),
    ]
