# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyBazaar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/properties/'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
