# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyBazaar', '0004_auto_20170305_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='propertytype',
        ),
    ]
